---
driver_plugin: lxc
use_sudo: true

platforms:
  - name: ubuntu-12.04
    driver_config:
      base_container: ubuntu_12.04
      username: ubuntu
      password: ubuntu

suites:
- name: default
  run_list: ["recipe[myface]"]
  attributes: {}
